### ISSUE TITLE
[Maintenance] Set up github templates for bug reports.

### ISSUE THREAD

**Issue by isabellabrookes** [PixelogicDev/Gruvee-Mobile#102]
https://github.com/pixelogicdev/Gruvee-Mobile/issues/templates/edit

You should do a general bug report but I think you should also add a Beta specific one for beta testers that includes both `beta` and `bug` labels.

Things I think you should ask for:
- Device
- OS
- Region/Location
- 4G/wifi speed

**Comment by adilanchian** [comment]
Will get this you all setup :)

**Comment by isabellabrookes** [comment]
Done. Added a `BETA` specific one too
