### ISSUE TITLE
[Release-1.0] Excessive Spotify permissions list

### ISSUE THREAD

**Issue by apust** [PixelogicDev/Gruvee-Mobile#103]
### What Happened

When signing up with Spotify, Grüvee asks for a lot of permissions, such as:

- Recently played music
- Top artists and genres
- Spotify subs count

### Problem

Those permissions are not used in current version in any way. I feel suspicious, when an app asks for more things than it should. It may be a turn off for other people as well.

**Comment by adilanchian** [comment]
Change these to ask for the following permissions:
```
        'user-library-modify',
        'user-library-read',
        'playlist-read-private',
        'playlist-read-collaborative',
        'playlist-modify-public',
        'playlist-modify-private',
        'user-read-email',
        'user-read-private'
```

I believe this makes a lot more sense based on what we are trying to do
