### ISSUE TITLE
[Bug] Spotify friendlyName never shows up

### ISSUE THREAD

**Issue by maxemiliang** [PixelogicDev/Gruvee-Mobile#107]
Not a big bug but annoying nonetheless.

- Oneplus 7T
- Android 
- Europe
- 4G and Wifi (400Mbps)

Attached screenshots
![lul](https://user-images.githubusercontent.com/7084690/80314380-fb3e6c00-87f9-11ea-945b-30fff81e7d2d.jpg)

**Comment by maxemiliang** [comment]
https://github.com/PixelogicDev/Gruvee-Mobile/blob/1bc67bc6fa29dcca58bd6de18e8e7b9147bc5408/app/components/Auth/components/Buttons/SocialAuthButton.js#L25

**Comment by isabellabrookes** [comment]
Can confirm also on OnePlus 7 - Oxygen OS 10.0.5

**Comment by adilanchian** [comment]
@maxemiliang assigning to you as you submitted a PR for this :)

**Comment by maxemiliang** [comment]
Closing as this is solved by #112.
