### ISSUE TITLE
Unable to login with Spotify for first time

### ISSUE THREAD

**Issue by DR-DinoMight** [PixelogicDev/Gruvee-Mobile#115]
**Describe the bug**
Unable to login in with Spotify for the first time, I've just downloaded the app and now just goes on a loop.

**To Reproduce**
1. First time login on a iOS device
2. Click on login in with Spotify 
3. Approve the request on Spotify's authorisation screen.
4. Go back to the App, through popup request.
5. Get sent back to the login screen and the loop begins again.

**Expected behavior**
Upon Approving the request should be allowed to proceed on into the App.

**Video**
https://share.getcloudapp.com/qGudXl27

**Desktop (please complete the following information):**
 - OS: IOS
 - Browser: Safari
 - Version 1.0

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: 13.3.1
 - Browser Safari

**Additional context**
Not sure if this will help, but i am in the UK region, and was on WIFI.

**Comment by mdeloughry** [comment]
Just updated the the correct build 😄.

The first three attempts still had the same behaviour but then the fourth attempt let me in!

**Comment by adilanchian** [comment]
Seems like there might have been an issue here based off of #119. Going to close this as a dupicate!
