### ISSUE TITLE
[BUG] Unable to login 

### ISSUE THREAD

**Issue by LuisACorreaCSUMB** [PixelogicDev/Gruvee-Mobile#119]
**Describe the bug**
Android application was not allowing me to login. Previously was unable to but now does not register login. 
Attempted Fixes:
- Cleared cache and closed out browsers & apps
- Reinstalled application
- Restarted phone after cache clear
- Created second Spotify account to test a different login method

**Smartphone (please complete the following information):**
 - Device: Samsung Note 9 Android version 10 FB Login & Spotify Login
-  Emulator : Nexus Android Version7 Spotify Login

https://drive.google.com/file/d/1YhnJWppqOv81XK6afRx4PjShZhrBWtXh/view?usp=sharing

**Comment by YouTwitFace** [comment]
I'm having the same problem on a Moto G7 Power with Android version 9.

**Comment by isakfk1234** [comment]
same. I have ios iphone 11.

**Comment by adilanchian** [comment]
New Android & iOS app have been pushed to testers to see if it works! Found two issues here:

1. When logging in with Facebook, Facebook deeplink adds a `#__=_` which breaks the entire code received back from spotify. I made sure to rip that out

2. Deep linking was happening on every rerender of the auth component. If spotify auth is called two quickly like that, it says hell no and returns an error. I moved this to the main App component and deep linking seems to be working fine on Android and iOS!

Please confirm and then I can resolve this if everything works!

**Comment by adilanchian** [comment]
Checked again this morning and not running into issues it seems. Going to close this out!
