### ISSUE TITLE
Clicking on Playlist displays the delete button.

### ISSUE THREAD

**Issue by fangskills** [PixelogicDev/Gruvee-Mobile#99]
When I click on a playlist, it displays the delete button and then takes me into the playlist contents.

![gruvee-playlist-bug](https://user-images.githubusercontent.com/37905409/80289584-f77ced80-8704-11ea-85fd-7249befe5d34.gif)

**Comment by adilanchian** [comment]
Thanks for this bug! We are actually already tracking this in #31 

So I am going to close out this issue (but probably keep the screen recording cuz its dope)
